name: CI for Chinese Festivals
on:
  push:
    paths:
      - '.github/workflows/**'
      - 'common/src/**'
      - 'common/build.gradle'
      - 'fabric/src/**'
      - 'fabric/build.gradle'
      - 'forge/src/**'
      - 'forge/build.gradle'
      - 'forge/gradle.properties'
      - 'build.gradle'
      - 'gradle.properties'
      - 'settings.properties'
    branches-ignore:
      - 'releases/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_RUN_NUMBER: ${{ vars.GITHUB_RUN_NUMBER }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set build number
        run: sed -i "s/undefined/$GITHUB_RUN_NUMBER/g" gradle.properties

      - name: Build
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: build

      - name: Copy Files
        run: |
          rm -rf build/libs/*
          mkdir build/libs/common
          mkdir build/libs/fabric
          mkdir build/libs/forge
          cp common/build/libs/*.jar build/libs/common/
          cp fabric/build/libs/*.jar build/libs/fabric/
          cp forge/build/libs/*.jar build/libs/forge/

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Artifact
          path: 'build/libs/*'